// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCg3mxNbbcz4bV3u7glXV0PySwLNT-HmY',
    appId: '1:361981046459:web:36c83107a01b7905df039e',
    messagingSenderId: '361981046459',
    projectId: 'get-instant-help',
    authDomain: 'get-instant-help.firebaseapp.com',
    storageBucket: 'get-instant-help.appspot.com',
    measurementId: 'G-4MQ99MVYQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZbC9W4Hv4iS5Wkm0GrDyiYMw2Jj51Kl0',
    appId: '1:361981046459:android:926e7d07e680ffc8df039e',
    messagingSenderId: '361981046459',
    projectId: 'get-instant-help',
    storageBucket: 'get-instant-help.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaTsvuJgWWhreZ9lhLJpHF2iJGNBo7ZA',
    appId: '1:361981046459:ios:73348e1b20cbc292df039e',
    messagingSenderId: '361981046459',
    projectId: 'get-instant-help',
    storageBucket: 'get-instant-help.appspot.com',
    iosClientId: '361981046459-30ckuuqb6mmskk2h9vdpb7jn1qdc8n4k.apps.googleusercontent.com',
    iosBundleId: 'io.github.imobasshir.getInstantHelp',
  );
}
